### ISSUE TITLE
the current disc is empty or not recognized as an sacd, please re-insert

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sacd-ripper/sacd-ripper#64]
```
What steps will reproduce the problem?
1. I can still rip discs
2. I am sometimes getting this message
3. When I re-insert it will usually see the disc

Is there a problem with the firmware installation or the sacd-ripper.pkg I 
installed. The version I used is the 0.30. I did reinstall that, but the 
problem seemed to improve, but it really is showing up again.

What version of the product are you using? On what operating system?
kmeaw 3.55 cfw 

Please provide any additional information below.
I did install the ps3 keys and everthing seemed fine. I also attempted to play 
a tiger woods game, but the system had trouble playing it. I am returning the 
disc, which was a used PGA '10. Could this have had an effect on the 
sacd-ripper?

I am also wondering if there is a problem with the disc drive or the 
sacd-ripper.pkg? Is this a know bug or issue?

Thanks,
Shawn


```

Original issue reported on code.google.com by `ingodido...@gmail.com` on 23 Mar 2013 at 4:53
- Merged into: #62

**Comment by misterfatch** [comment]
Hi there, I had trouble to be able to read SACD in sacd ripper v0.37 in my Rogero 3.55 v4, and I looked at MANY websites, and my suggestions I learned was someone talked about an LV2 encryption problem that led the BD drive not to recognize the SACD, and also if the system if detecting the PS3 as too hot (if we tried to modify the fan control) the SACD woul'nt also be read.



So what I did:

1) Put system fan control to max, reinstalled latest OFW 

2) Played a bit of Call of duty MW3 so that the fans turn on automatically to protect PS3 from overheat ( I heard it could kill the CPU, and from the many OFW/CFW installs I made, the fans did not change speed during install of FW: I'm afraid the PS3 fan control stays the same during install (IMO)

3) On the browser of the PS3, went to PS3xploit.com and allowed me to install a cfw (flash memory - download from HTTPS -when done, click flash memory - Apply loaded patch : Reboot the console when asked

4) Play a little Cod MW3 for fans

5) install from XMB PS3 menus the downgrader: https://www.mediafire.com/file/vfplvjfl9kitqie/355rogerodowngrader.PUP/file

[ If it did not work accept the downgrade, first install CFW https://www.mediafire.com/file/cgpats300d4c8xu/488cfw.PUP/file and enable qa flag with https://www.mediafire.com/file/5cfsrw0k02f0x5b/Habib-QA_Toggle-4.21%2B%28standalone%29.pkg.334.v1.0_brewology_com.pkg/file ]

6) Check if SACD v0.37 works correctly (0.38 is erratic working IMO, for me v0.37 is the best), and unzip the keys on the root of your FAT32 formatted USB drive: https://www.mediafire.com/file/9yk2vn0kb28kk46/sacd-ripper.pkg/file ; https://www.mediafire.com/file/oyg5l2zinmgx0an/ps3keys.rar/file

7) If everything works fine, install Rogero 3.55 v4, try your SACD, and everything should be fine then. If not Start back from Step 1

https://www.mediafire.com/file/8nijzhxgoocolb1/355rogerov4.PUP/file





Enjoy your SACD ripper fellas
