### ISSUE TITLE
Linux Install

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sacd-ripper/sacd-ripper#72]
```
I am attempting to install sacd-extract on headless Debian Linux Mint. 

I am getting an error from cmake. What maybe the cause of this issue? Do I also 
require PSL1GHT if I am not installing for PS3?

Here's my process so far :

henry@audio ~/ $ svn checkout http://sacd-ripper.googlecode.com/svn/trunk/ 
sacd-ripper
henry@audio ~ $ cd sacd-ripper/
henry@audio ~/sacd-ripper $ cmake .
CMake Error: The source directory "/home/henry/sacd-ripper" does not appear to 
contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.


```

Original issue reported on code.google.com by `henry...@gmail.com` on 11 Sep 2013 at 11:15

**Comment by remenor** [comment]
The topic is closed, but:
If the code source downloaded from here (instead of SVN) it is possible to compile in any directory, as normal user. 
$cd sacd-ripper/tools/sacd_extract/
$cmake .
$make
And only copy the binary (as user root or with sudo) in his PATH, eg:
#cp sacd_extract /usr/local/bin
or
$sudo cp sacd_extract /usr/local/bin
Sorry for my english
