### ISSUE TITLE
Problem when compile sacd_extract on Ubuntu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sacd-ripper/sacd-ripper#73]
```
What steps will reproduce the problem?
1.
First, compile libiconv, in my console:
$cd libiconv-1.14/
$configure
$make && make install

then compile sacd-ripper:
$cd sacd-ripper/
$svn update
$cd tools/sacd_extract
$cmake .
$make clean
$make

3.
What is the expected output? What do you see instead?
I expected it build success, but it failed.

What version of the product are you using? On what operating system?
sacd-ripper subversion r395 on Ubuntu 12.04 LTS,
gcc 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
cmake version 2.8.11.2
gnu libiconv 1.14

Please provide any additional information below.
When I add ' -liconv' to CMakeLists.txt, then
$cmake .
$make clean
$make
I get the compiled binary file.
Please see the attach file. Thanks.

```

Original issue reported on code.google.com by `mike2718` on 24 Sep 2013 at 5:44

Attachments:
- [CMakeLists.txt.diff](https://storage.googleapis.com/google-code-attachments/sacd-ripper/issue-73/comment-0/CMakeLists.txt.diff)

**Comment by remenor** [comment]
The topic is closed, but:
If the code source downloaded from here (instead of SVN) it is possible to compile in any directory, as normal user. 
$cd sacd-ripper/tools/sacd_extract/
$cmake .
$make
And only copy the binary (as user root or with sudo) in his PATH, eg:
#cp sacd_extract /usr/local/bin
or
$sudo cp sacd_extract /usr/local/bin
Sorry for my english
